export const xAccounts = [
  { handle: 'deepseek_ai', name: 'DeepSeek', type: 'Asian lab', region: 'CN', tier: 'core' },
  { handle: 'Alibaba_Qwen', name: 'Qwen (Alibaba)', type: 'Asian lab', region: 'CN', tier: 'core' },
  { handle: 'Kimi_Moonshot', name: 'Kimi (Moonshot AI)', type: 'Asian lab', region: 'CN', tier: 'core' },
  { handle: 'Zai_org', name: 'Z.ai (Zhipu, GLM)', type: 'Asian lab', region: 'CN', tier: 'secondary' },
  { handle: 'MiniMax_AI', name: 'MiniMax', type: 'Asian lab', region: 'CN', tier: 'secondary' },
  { handle: 'TencentHunyuan', name: 'Tencent Hunyuan', type: 'Asian lab', region: 'CN', tier: 'secondary' },
  { handle: 'StepFun_ai', name: 'StepFun', type: 'Asian lab', region: 'CN', tier: 'signal only' },
  { handle: 'SakanaAILabs', name: 'Sakana AI', type: 'Asian lab', region: 'JP', tier: 'secondary' },
  { handle: 'SarvamAI', name: 'Sarvam', type: 'Asian lab', region: 'IN', tier: 'secondary' },
  { handle: 'hardmaru', name: 'David Ha (Sakana AI CEO)', type: 'Asian lab researcher', region: 'JP', tier: 'secondary' },
  { handle: 'JustinLin610', name: 'Junyang Lin', type: 'Asian lab researcher', region: 'CN', tier: 'signal only' },
  { handle: 'kaifulee', name: 'Kai-Fu Lee', type: 'Asian AI leader', region: 'CN', tier: 'signal only' },
  { handle: 'EleanorOlcott', name: 'Eleanor Olcott (FT)', type: 'Journalist', region: 'CN', tier: 'secondary' },
  { handle: 'ZeyiYang', name: 'Zeyi Yang (NYT)', type: 'Journalist', region: 'CN', tier: 'secondary' },
  { handle: 'SCMPTech', name: 'SCMP Tech', type: 'Journalist/outlet', region: 'HK', tier: 'secondary' },
  { handle: 'restofworld', name: 'Rest of World', type: 'Journalist/outlet', region: 'Asia', tier: 'signal only' },
  { handle: 'poezhao0605', name: 'Poe Zhao', type: 'Analyst', region: 'CN', tier: 'secondary' },
  { handle: 'kevinsxu', name: 'Kevin S. Xu', type: 'Analyst/investor', region: 'CN, US', tier: 'secondary' },
  { handle: 'jjding99', name: 'Jeffrey Ding (ChinAI)', type: 'Researcher', region: 'CN', tier: 'secondary' },
  { handle: 'kyleichan', name: 'Kyle Chan (Brookings)', type: 'Researcher', region: 'CN', tier: 'secondary' },
  { handle: 'mattsheehan88', name: 'Matt Sheehan (Carnegie)', type: 'Researcher', region: 'CN', tier: 'secondary' },
  { handle: 'ruima', name: 'Rui Ma (Tech Buzz China)', type: 'Analyst', region: 'CN', tier: 'secondary' },
  { handle: 'jordanschneider', name: 'Jordan Schneider (ChinaTalk)', type: 'Analyst', region: 'CN', tier: 'signal only' },
  { handle: 'ZhihuFrontier', name: 'Zhihu Frontier', type: 'Community', region: 'CN', tier: 'signal only' },
  { handle: 'arena', name: 'Arena (LMArena)', type: 'Benchmark', region: 'Global', tier: 'signal only' },
] as const

export const xSearchQueries = [
  '(DeepSeek OR Qwen OR Kimi OR GLM OR MiniMax OR Hunyuan OR Doubao OR ERNIE OR StepFun) (release OR launch OR "open source" OR "open weights") -is:retweet -is:reply lang:en',
  '("Hong Kong" OR HKMA OR Cyberport OR HKSTP OR "Digital Policy Office") (AI OR "generative AI" OR LLM) -is:retweet lang:en',
  '(Singapore OR IMDA OR "SEA-LION" OR Indonesia OR Vietnam OR Malaysia OR Sarvam OR IndiaAI) ("AI model" OR LLM OR "generative AI") -is:retweet lang:en',
  '(Sakana OR SoftBank OR EXAONE OR HyperCLOVA OR Kakao OR "SK hynix") (AI OR LLM) -is:retweet lang:en',
  '(大模型 OR 开源模型) (发布 OR 开源) -is:retweet lang:zh',
] as const
